@startuml
skinparam classAttributeIconSize 0

class Seat {
    - char row
    - int seatNumber
    - boolean isAllocated
    - String customerId

    + Seat(row : char, number : int) : void
    + isAllocated() : boolean
    + allocate(customerId : String) : void
    + getCustomer() : String
}

interface SeatingPlanInterface {
    + getAvailableSeatCount () : int
    + getAvailableSeats() : List<String>
    + reserveSeats(seatNumbers : List<String>, customerId : String) : void
}

class SeatingPlan implements SeatingPlanInterface{
    - LinkedHashMap<String, Seat> seats
    - char maxRowLetter
    - int maxSeatsPerRow
    - String validRows

    - createSeatingPlan()

    + SeatingPlan (maxRow : char, maxSeatsPerRow : int)
}

class Movie {
    - String id
    - String movieName
    - DateTime showTime
    - SeatingPlan seatingPlan

    + Movie(movieId : String, movieName : String, showTime : DateTime)
    + getMovieId() : String
    + getShowTime() : DateTime
    + getName() : String
    + getSeatingPlan() : SeatingPlan
}

interface CinemaInterface {
    + getName () : String
    + getSeatingPlan () : SeatingPlan
}

class Cinema implements CinemaInterface {
    - String cinemaName

    + Cinema (name : String)
}

class BookingService {
    - Cinema cinema
    - List<Movie> movieList
    - HashMap<String,Customer> customers

    + BookingService (cinema : Cinema)
    + getMovies() : List<Movie>
    + addMovie(movieName : String, showTime : DateTime)
    + getAvailableMovies() : List<Movie>
    + bookSeats(customerId : String, numberOfSeats : int) : boolean
    + getCustomers() : List<Customer>
}

class Customer {
    - String id
    - List<Tickets> tickets

    + Customer(customerId : String)
    + addTicket(ticket : Ticket) : void
    + getTickets() : List<Tickets>
}

class Ticket {
    - String movieName
    - String seats
    - LocalDateTime showTime

    + Ticket(movieName : String, seats : String, showTime : LocalDateTime)
}

BookingService -left- SeatingPlan
BookingService -up- Movie
BookingService -down- Cinema
BookingService -right- Ticket
BookingService - Customer
SeatingPlan -down- Seat
Ticket -down- Customer
CinemaInterface -right[hidden]- Cinema
@enduml