@startuml
skinparam classAttributeIconSize 0

class Seat {
    - char row
    - int seatNumber
    - boolean isAllocated
    - String customerId

    + Seat(row : char, number : int) : void
    + isAllocated() : boolean
    + allocate(customerId : String) : void
    + getCustomer() : String
}

class SeatingPlan {
    - LinkedHashMap<String, Seat> seats
    - char maxRowLetter
    - int maxSeatsPerRow
    - String VALID_ROWS = "ABC"

    - createSeatingPlan()

    + SeatingPlan (maxRow : char, maxSeatsPerRow : int)
    + getAvailableSeatCount () : int
    + getAvailableSeats() : List<String>
    + reserveSeats(seatNumbers : List<String>, customerId : String) : void
}

class Movie {
    - String id
    - String movieName
    - DateTime showTime

    + Movie(movieId : String, movieName : String, showTime : DateTime)
    + getMovieId() : String
    + getShowTime() : DateTime
    + getName() : String
}

class Cinema {
    - String cinemaName
    - List<Movie> movies

    + Cinema (name : String)
    + getMovies() : List<Movie>
    + addMovie(movieName : String, showTime : DateTime)
}

class BookingService {
    - Cinema cinema

    + BookingService (cinema : Cinema)
    + getAvailableMovies() : List<Movie>
    + bookSeats(customerId : String, numberOfSeats : int) : boolean
}

class Customer {
    - String id
    - List<String> tickets
}


@enduml